### PR TITLE
fix(docs): Change channel:analytics, bumping common ver

### PR DESCRIPTION
**Pull request by williamtdr**
New version is 5.0.5, see [linked PR](https://github.com/mixer/common/pull/68).

### CODE REVIEW

**Comment by ProbablePrime** [comment]
ooft, thats quite a version bump. Did you check everything looked good?

**Comment by williamtdr** [comment]
@ProbablePrime I know :( Can't check easily until the other PR gets approved and npm syncs... otherwise I'll have to the play with `link` and such

**Comment by williamtdr** [comment]
@ProbablePrime - all unit tests are passing. tested the result on local, and the version bump doesn't appear to affect anything. The scope is removed from `/reference/oauth/index.html#oauth_scopes` as expected.

**Comment by ProbablePrime** [comment]
Alright then thanks :)!

**Comment by SimonSchick** [comment]
@ProbablePrime the major bump came from removing lodash and jojen from common, we should be good.

**Pull request merged**
